import type { ExerciseDef } from './exerciseLibrary';

/**
 * Exercise definitions for the CaliMove catalogue.
 * IDs use calimove_<snake_case> format.
 * Source: 'calimove'
 */
export const CALIMOVE_EXERCISE_LIBRARY: ExerciseDef[] = [
  // ── Push ────────────────────────────────────────────────────────────────────
  {
    id: 'calimove_incline_push_up',
    name: 'Incline Push Up',
    defaultPhase: 'push',
    icon: '↗',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['push', 'upper', 'level1'],
    source: 'calimove',
    muscles: { primary: ['chest', 'front_delt'], secondary: ['triceps'] },
  },
  {
    id: 'calimove_push_up',
    name: 'Push Up',
    defaultPhase: 'push',
    icon: '⬇',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['push', 'upper', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['chest', 'front_delt'], secondary: ['triceps'] },
  },
  {
    id: 'calimove_side_to_side_push_up',
    name: 'Side To Side Push Up',
    defaultPhase: 'push',
    icon: '↔',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['push', 'upper', 'level2'],
    source: 'calimove',
    muscles: { primary: ['chest', 'front_delt'], secondary: ['triceps', 'side_delt'] },
  },
  {
    id: 'calimove_dip',
    name: 'Dip',
    defaultPhase: 'push',
    icon: 'D',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['push', 'upper', 'level2'],
    source: 'calimove',
    muscles: { primary: ['chest', 'triceps'], secondary: ['front_delt'] },
  },
  {
    id: 'calimove_band_ass_dip',
    name: 'Band Ass Dip',
    defaultPhase: 'push',
    icon: 'B',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['push', 'upper', 'level1', 'assisted'],
    source: 'calimove',
    muscles: { primary: ['chest', 'triceps'], secondary: ['front_delt'] },
  },
  // ── Pull ────────────────────────────────────────────────────────────────────
  {
    id: 'calimove_bodyrow',
    name: 'Bodyrow',
    defaultPhase: 'push',
    icon: '↓',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['pull', 'upper', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['lats', 'traps'], secondary: ['biceps', 'rear_delt'] },
  },
  {
    id: 'calimove_archer_bodyrow',
    name: 'Archer Bodyrow',
    defaultPhase: 'push',
    icon: '🏹',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['pull', 'upper', 'level2'],
    source: 'calimove',
    muscles: { primary: ['lats', 'rear_delt'], secondary: ['biceps', 'traps'] },
  },
  {
    id: 'calimove_pull_up',
    name: 'Pull Up',
    defaultPhase: 'push',
    icon: '⬆',
    defaultDurationSec: 0,
    defaultReps: 6,
    tags: ['pull', 'upper', 'level2'],
    source: 'calimove',
    muscles: { primary: ['lats', 'biceps'], secondary: ['traps', 'rear_delt'] },
  },
  {
    id: 'calimove_band_ass_pull_up',
    name: 'Band Ass Pull Up',
    defaultPhase: 'push',
    icon: 'P',
    defaultDurationSec: 0,
    defaultReps: 6,
    tags: ['pull', 'upper', 'level1', 'assisted'],
    source: 'calimove',
    muscles: { primary: ['lats', 'biceps'], secondary: ['traps'] },
  },
  // ── Isometric Upper ─────────────────────────────────────────────────────────
  {
    id: 'calimove_active_hang',
    name: 'Active Hang',
    defaultPhase: 'practice',
    icon: 'Y',
    defaultDurationSec: 60,
    defaultReps: 0,
    tags: ['isometric_upper', 'upper', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['lats', 'traps'], secondary: ['forearms'] },
  },
  {
    id: 'calimove_pike_stand',
    name: 'Pike Stand',
    defaultPhase: 'practice',
    icon: '^',
    defaultDurationSec: 60,
    defaultReps: 0,
    tags: ['isometric_upper', 'upper', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['front_delt', 'traps'], secondary: ['core'] },
  },
  // ── Squat ───────────────────────────────────────────────────────────────────
  {
    id: 'calimove_squat',
    name: 'Squat',
    defaultPhase: 'push',
    icon: '🦵',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['squat', 'lower', 'level1'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'calimove_side_squat',
    name: 'Side Squat',
    defaultPhase: 'push',
    icon: '↙',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['squat', 'lower', 'level1'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'calimove_jumping_squat',
    name: 'Jumping Squat',
    defaultPhase: 'push',
    icon: '⬆',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['squat', 'lower', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['calves', 'hamstrings'] },
  },
  {
    id: 'calimove_archer_squat',
    name: 'Archer Squat',
    defaultPhase: 'push',
    icon: '🏹',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['squat', 'lower', 'level2'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'calimove_elevated_pistol_squat',
    name: 'Elevated Pistol Squat',
    defaultPhase: 'push',
    icon: '🎯',
    defaultDurationSec: 0,
    defaultReps: 6,
    tags: ['squat', 'lower', 'level2'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
  },
  // ── Hinge ───────────────────────────────────────────────────────────────────
  {
    id: 'calimove_easy_bridge_raise',
    name: 'Easy Bridge Raise',
    defaultPhase: 'push',
    icon: '🌉',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['hinge', 'lower', 'level1'],
    source: 'calimove',
    muscles: { primary: ['glutes', 'hamstrings'], secondary: ['lower_back'] },
  },
  {
    id: 'calimove_lunge',
    name: 'Lunge',
    defaultPhase: 'push',
    icon: '/',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['hinge', 'lower', 'level1'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'calimove_jumping_lunge',
    name: 'Jumping Lunge',
    defaultPhase: 'push',
    icon: '!',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['hinge', 'lower', 'level1'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
  },
  {
    id: 'calimove_step_up',
    name: 'Step Up',
    defaultPhase: 'push',
    icon: '↑',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['hinge', 'lower', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'calimove_sl_glute_bridge_raise',
    name: 'Sl Glute Bridge Raise',
    defaultPhase: 'push',
    icon: '🌉',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['hinge', 'lower', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['glutes', 'hamstrings'], secondary: ['lower_back'] },
  },
  {
    id: 'calimove_swimmer',
    name: 'Swimmer',
    defaultPhase: 'push',
    icon: '🏊',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['hinge', 'lower', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['lower_back', 'glutes'], secondary: ['traps', 'rear_delt'] },
  },
  {
    id: 'calimove_arch_up',
    name: 'Arch Up',
    defaultPhase: 'push',
    icon: '⌒',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['hinge', 'lower', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['lower_back', 'glutes'], secondary: ['hamstrings'] },
  },
  // ── Isometric Lower ─────────────────────────────────────────────────────────
  {
    id: 'calimove_deep_squat',
    name: 'Deep Squat',
    defaultPhase: 'practice',
    icon: '⬇',
    defaultDurationSec: 60,
    defaultReps: 0,
    tags: ['isometric_lower', 'lower', 'level2'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'] },
  },
  {
    id: 'calimove_horse_stance',
    name: 'Horse Stance',
    defaultPhase: 'practice',
    icon: '#',
    defaultDurationSec: 60,
    defaultReps: 0,
    tags: ['isometric_lower', 'lower', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
  },
  {
    id: 'calimove_easy_bridge',
    name: 'Easy Bridge',
    defaultPhase: 'practice',
    icon: '🌉',
    defaultDurationSec: 60,
    defaultReps: 0,
    tags: ['isometric_lower', 'lower', 'level1'],
    source: 'calimove',
    muscles: { primary: ['glutes', 'hamstrings'], secondary: ['lower_back'] },
  },
  // ── Core ────────────────────────────────────────────────────────────────────
  {
    id: 'calimove_hollow_body_crunch',
    name: 'Hollow Body Crunch',
    defaultPhase: 'push',
    icon: '🥁',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['core', 'level1', 'level2'],
    source: 'calimove',
    muscles: { primary: ['core'], secondary: [] },
  },
  {
    id: 'calimove_lying_knee_twist',
    name: 'Lying Knee Twist',
    defaultPhase: 'push',
    icon: '🔀',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['core', 'level2'],
    source: 'calimove',
    muscles: { primary: ['core'], secondary: ['lower_back'] },
  },
  {
    id: 'calimove_knee_to_elbow_plank',
    name: 'Knee To Elbow Plank',
    defaultPhase: 'push',
    icon: '📐',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['core', 'level1'],
    source: 'calimove',
    muscles: { primary: ['core'], secondary: ['front_delt'] },
  },
  {
    id: 'calimove_prone_arm_circles',
    name: 'Prone Arm Circles',
    defaultPhase: 'push',
    icon: '⭕',
    defaultDurationSec: 0,
    defaultReps: 20,
    tags: ['core', 'level1'],
    source: 'calimove',
    muscles: { primary: ['core', 'lower_back'], secondary: ['rear_delt'] },
  },
  {
    id: 'calimove_hanging_leg_raise',
    name: 'Hanging Leg Raise',
    defaultPhase: 'push',
    icon: '🦵',
    defaultDurationSec: 0,
    defaultReps: 8,
    tags: ['core', 'level1'],
    source: 'calimove',
    muscles: { primary: ['core'], secondary: ['forearms', 'lats'] },
  },
  // ── Isometric Core ──────────────────────────────────────────────────────────
  {
    id: 'calimove_hollow_body',
    name: 'Hollow Body',
    defaultPhase: 'practice',
    icon: '🥁',
    defaultDurationSec: 60,
    defaultReps: 0,
    tags: ['isometric_core', 'core', 'level2'],
    source: 'calimove',
    muscles: { primary: ['core'], secondary: [] },
  },
  {
    id: 'calimove_plank',
    name: 'Plank',
    defaultPhase: 'practice',
    icon: '🧊',
    defaultDurationSec: 60,
    defaultReps: 0,
    tags: ['isometric_core', 'core', 'level1'],
    source: 'calimove',
    muscles: { primary: ['core'], secondary: ['front_delt'] },
  },
];
